apiVersion: v1
kind: Secret
metadata:
  name: {{ template "krwordcloud.fullname" . }}-api-secret
  labels: {{- include "krwordcloud.api.labels" . | nindent 4 }}
type: Opaque
data:
  bucket-password: cGFzc3dvcmQ= #password