app:
<<<<<<< HEAD
=======
  host: http://localhost
  port: 3000
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
  image:
    name: krwordcloud/app
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  service:
    type: NodePort 
    name: krwordcloud-app
    port: 80
<<<<<<< HEAD
    nodePort: 30000
=======
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
  livenessProbe:
    enabled: false
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources: {}
  livenessProbeHeaders: {}
  readinessProbeHeaders: {}
  healthcheckHttps: false
api:
  host: http://localhost
  port: 4000
  image:
    name: krwordcloud/api
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  service:
    type: NodePort 
    name: krwordcloud-api
<<<<<<< HEAD
    port: 8080
    nodePort: 30001
=======
    port: 4000
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
  livenessProbe:
    enabled: false
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources: {}
  livenessProbeHeaders: {}
  readinessProbeHeaders: {}
  healthcheckHttps: false
ingress:
<<<<<<< HEAD
  enabled: false
=======
  enabled: true
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
  tls: false
  hosts:
    - host: localhost:3000 
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: krwordlcoud-app
              port: 80
    - host: localhost:4000
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: krwordlcoud-api
              port: 4000

airflow:
<<<<<<< HEAD
=======
  nameOverride: airflow
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
  ###################################
  # Airflow - Common Configs
  ###################################
  airflow:
<<<<<<< HEAD
    nameOverride: airflow
=======
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
    ## the airflow executor type to use
    ##
    executor: PythonExecutor

    ## the fernet key used to encrypt the connections in the database
    ##
    fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="

    extraVolumeMounts: # this will get the volume and mount it to that path in the container
      - name: dags
<<<<<<< HEAD
        mountPath: "../airflow/dags"  # location in the container it will put the directory mentioned below.
=======
        mountPath: "$HOME/workspace/git/wordcloud/airflow/dags"  # location in the container it will put the directory mentioned below.
>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531

    extraVolumes: # this will create the volume from the directory
      - name: dags
        hostPath:
          path: /opt/airflow/dags

    ## environment variables for the web/scheduler/worker Pods (for airflow configs)
    ##
    config:
      # Security
      AIRFLOW__CORE__SECURE_MODE: "True"
      AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW__WEBSERVER__RBAC: "False"

      # DAGS
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      ## Disable noisy "Handling signal: ttou" Gunicorn log messages
      GUNICORN_CMD_ARGS: "--log-level WARNING"
    env:
      KAFKA_BROKERS:
        - "kafka-broker"

  ###################################
  # Airflow - Scheduler Configs
  ###################################
  scheduler:
<<<<<<< HEAD
    nameOverride: "airflow-scheduler"
=======

>>>>>>> 9c280ca8cb5d26bc0449c4e9f0d691169c1b0531
    ## custom airflow connections for the airflow scheduler
    ##
    # connections:
    #   - id: my_aws
    #     type: aws
    #     extra: |
    #       {
    #         "aws_access_key_id": "XXXXXXXXXXXXXXXXXXX",
    #         "aws_secret_access_key": "XXXXXXXXXXXXXXX",
    #         "region_name":"eu-central-1"
    #       }
    ## custom airflow variables for the airflow scheduler
    ##
    variables: |
      { "environment": "dev" }
    ## custom airflow pools for the airflow scheduler
    ##
    pools: |
      {
        "example": {
          "description": "This is an example pool with 2 slots.",
          "slots": 2
        }
      }
  ###################################
  # Airflow - WebUI Configs
  ###################################
  web:
    nameOverride: "airflow-web"
    ## configs for the Service of the web Pods
    ##
    service:
      type: NodePort
      nodePort:
        http: 30400

  ###################################
  # Airflow - Worker Configs
  ###################################
  workers:
    nameOverride: "airflow-workers"
    ## the number of workers Pods to run
    ##
    replicas: 1

  ###################################
  # Airflow - DAGs Configs
  ###################################
  dags:
    persistence:
      enabled: true
      

  ###################################
  # Database - PostgreSQL Chart
  ###################################
  postgresql:
    enabled: false

  ###################################
  # Database - Redis Chart
  ###################################
  redis:
    enabled: true

  serviceMonitor:
    enabled: true 

cp-helm-charts:
  cp-kafka:
    # nameOverride: kafka
    brokers: 1
  cp-kafka-connect:
    # nameOverride: kafka-connect 
    kafka:
      bootstrapServers: krwordcloud-kafka:9092 
    cp-schema-registry:
      url: http://krwordcloud-kafka-schema-registry:8081
  cp-zookeeper:
    # nameOverride: kafka-zookeeper
    enabled: true
    servers: 1
  cp-schema-registry:
    # nameOverride: kafka-schema-registry

hdfs:
  persistence:
    nameNode:
      enabled: true
      storageClass: standard
    dataNode:
      enabled: true
      storageClass: standard

couchbase-operator:
  # Select what to install
  install:
    # install the couchbase operator
    couchbaseOperator: true
    # install the admission controller
    admissionController: true
    # install couchbase cluster
    couchbaseCluster: true
    # install sync gateway
    syncGateway: false
  cluster:
    monitoring:
      prometheus:
        # defines whether Prometheus metric collection is enabled
        enabled: true
        # image used by the Operator to perform metric collection
        # (injected as a "sidecar" in each Couchbase Server Pod)
        image: couchbase/exporter:1.0.3

prometheus:
  server:
    nameOverride: prometheus
    service:
      name: web
      type: NodePort
      nodePort: 30501
      port: 9090
      protocol: TCP
  alertmanager:
    persistentVolume:
      storageClass: standard

grafana:
  nameOverride: grafana
  service:
    type: NodePort
    nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 3000
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  datasources:
   datasources.yaml:
     apiVersion: 1
     datasources:
       - name: Prometheus
         type: prometheus
         url: http://krwordcloud-prometheus-server
         access: proxy
         isDefault: true
