enabled: true
tls: false
hosts:
  - host: app
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port: 3000
  - host: api
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port: 4000
